# Generated by Django 3.2.16 on 2023-02-22 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OFF_THE_SADDLE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climb', to='OFF_THE_SADDLE.climb')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
