# Generated by Django 3.2.16 on 2023-06-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OFF_THE_SADDLE', '0002_ridetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='climb_Difficulty',
            new_name='climb_difficulty',
        ),
        migrations.RenameField(
            model_name='climb',
            old_name='climb_Elevationgain',
            new_name='climb_elevation_gain',
        ),
        migrations.RenameField(
            model_name='climb',
            old_name='climb_Length',
            new_name='climb_length',
        ),
        migrations.RenameField(
            model_name='climb',
            old_name='climb_Surface',
            new_name='climb_surface',
        ),
    ]
