# Generated by Django 3.2.16 on 2023-02-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OFF_THE_SADDLE', '0002_auto_20230219_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='climb_elevationgain',
            new_name='climb_elevationgain_in_meters',
        ),
        migrations.RenameField(
            model_name='climb',
            old_name='climb_length',
            new_name='climb_length_in_miles',
        ),
    ]
