# Generated by Django 3.2.16 on 2023-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OFF_THE_SADDLE', '0003_auto_20230221_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='climb_KOMQOM_in_minutes',
            field=models.CharField(default='1', max_length=250),
        ),
    ]
