# Generated by Django 3.2.16 on 2023-02-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OFF_THE_SADDLE', '0004_climb_climb_komqom_in_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='climb_difficulty',
            new_name='climb_Difficulty',
        ),
        migrations.RenameField(
            model_name='climb',
            old_name='climb_elevationgain_in_meters',
            new_name='climb_Elevationgain_in_meters',
        ),
        migrations.RenameField(
            model_name='climb',
            old_name='climb_length_in_miles',
            new_name='climb_Length_in_miles',
        ),
        migrations.RenameField(
            model_name='climb',
            old_name='climb_surface',
            new_name='climb_Surface',
        ),
    ]
