# Generated by Django 3.2.16 on 2023-02-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OFF_THE_SADDLE', '0005_auto_20230221_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='climb_KOMQOM_in_minutes',
            new_name='climb_Elevationgain',
        ),
        migrations.RemoveField(
            model_name='climb',
            name='climb_Elevationgain_in_meters',
        ),
        migrations.AddField(
            model_name='climb',
            name='climb_KOMQOMtime',
            field=models.CharField(default='1', max_length=250),
        ),
    ]
