# Generated by Django 3.2.16 on 2023-02-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OFF_THE_SADDLE', '0006_auto_20230222_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='climb_KOMQOMtime',
            new_name='climb_KOMQOM',
        ),
    ]
