# Generated by Django 3.2.16 on 2023-02-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OFF_THE_SADDLE', '0007_rename_climb_komqomtime_climb_climb_komqom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='climb_KOMQOM',
            new_name='climb_KOMQOM_in_minutes',
        ),
        migrations.AlterField(
            model_name='climb',
            name='climb_Elevationgain',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
