# Generated by Django 3.2.16 on 2023-02-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OFF_THE_SADDLE', '0008_auto_20230222_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='climb_Elevationgain',
            new_name='climb_Elevationgain_in_meters',
        ),
    ]
